name: 'Terraform Discover'
description: 'Find subpaths containing terraform configs'

outputs:
  random-number:
    description: "List of terraform paths"
    value: ${{ steps.dirs.outputs.terraform_dirs }}
runs:
  using: "composite"
  steps:
    - name: Checkout code
        uses: actions/checkout@v4

    - name: Discover Terraform subdirectories
      id: dirs
      run: |
        terraform_dirs=$(find . -type f -name "*.tf" -exec dirname {} \; | sort -u | grep -v "modules/")
        echo "terraform_dirs=$terraform_dirs"
        terraform_dirs_json=$(jq -ncR '[inputs]' <<< "$terraform_dirs")
        echo "terraform_dirs=$terraform_dirs_json" >> $GITHUB_OUTPUT