name: Build and push container image to GHCR
run-name: Build and push container image by ${{ github.actor }}

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: false
        default: ""
      repository:
        type: string
        required: false
        default: ""
      fetch-depth:
        type: number
        required: false
        default: 1
        description: "Fetch depth, defaults to 1 (shallow clone)."

permissions:
  id-token: write
  contents: read

jobs:
  check:
    name: Check if container image already exists
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        id: checkout-for-sha
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || github.ref_name }}
          fetch-depth: ${{ inputs.fetch-depth }}
      - name: debug
        run: |
          pwd
          ls -la
